name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Run Tests
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run: mvn -B package -P prod --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ska-aleksej
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/ska-aleksej/friday-words:latest

  deploy:
    needs: test-and-build
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Принудительно загружаем последнюю версию образа
            docker pull ghcr.io/ska-aleksej/friday-words:latest
            
            # Остановка и удаление только если контейнер существует
            if docker inspect friday-words &>/dev/null; then
              docker stop friday-words || true
              docker rm friday-words || true
            fi

            # Запуск с явным указанием политики перезапуска
            docker run -d \
              --name friday-words \
              --restart unless-stopped \
              -p 8080:8080 \
              -e "SPRING_PROFILES_ACTIVE=prod" \
              -v /etc/timezone:/etc/timezone:ro \
              ghcr.io/ska-aleksej/friday-words:latest

            # Очистка старых образов
            docker image prune -f